version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/argus/
    binary: argus
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: lbarahona
    name: argus

brews:
  - repository:
      owner: lbarahona
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/lbarahona/argus"
    description: "AI-powered observability CLI for SREs"
    license: "MIT"
    test: |
      assert_match "argus", shell_output("#{bin}/argus version 2>&1", 0)
